


DROP TABLE IF EXISTS TitleGenres;
DROP TABLE IF EXISTS TitleWriters;
DROP TABLE IF EXISTS TitleDirectors;
DROP TABLE IF EXISTS TitleEpisodes;
DROP TABLE IF EXISTS PeopleTitles;
DROP TABLE IF EXISTS People;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Ratings;

DROP TABLE IF EXISTS Titles;